### ISSUE TITLE
Support for PHP 7.2

### ISSUE THREAD

**Issue by josefglatz** [xperseguers/t3ext-extractor#1]
Hi Xavier,

is there a plan to support PHP 7.2? What about allowing 7.2 within composer.json in dev-master?

**Comment by xperseguers** [comment]
It should work, feel free to confirm and provide a PR.

**Comment by 7elix** [comment]
Thanks for the patch! Are you planning a release / tag with the new compatibility constraints @xperseguers

**Comment by xperseguers** [comment]
done.
