### ISSUE TITLE
Bump composer.json to PHP 7.3

### ISSUE THREAD

**Issue by LeoniePhiline** [xperseguers/t3ext-extractor#12]
Hi! :)

I find extractor working with PHP 7.3. 

Could you verify - and then update composer.json? 

Thanks!

**Comment by LeoniePhiline** [comment]
*ping*

**Comment by xperseguers** [comment]
Fixed since commit 1c8f491d

**Comment by LeoniePhiline** [comment]
@xperseguers 
Would you please release a new version to packagist?
Thank you!
