### ISSUE TITLE
TYPO3 9.5: Uploads show Status Code 500

### ISSUE THREAD

**Issue by josefglatz** [xperseguers/t3ext-extractor#13]
hey Xavier,

when using the extension in TYPO3 9 LTS almost no file upload shows a successful process and doesn't show a notification message in the TYPO3 backend to the editor.

* sometimes an upload works
* sometimes every file upload fails in the UI without successful uploading to server
* sometimes every file upload files in the UI but the files are there in the end

The screenshot shows the 2nd mentioned behaviour.

![image](https://user-images.githubusercontent.com/2861556/52397298-2fbeee80-2ab5-11e9-8329-dd2ada147b6f.png)

The extConf looks like

```php
        'extractor' => [
            'enable_tika' => 0,
            'enable_tools_exiftool' => 0,
            'enable_tools_pdfinfo' => 0,
            'enable_php' => 1,
            'auto_extract' => 0,
            'tika_mode' => 'jar',
            'tika_jar_path' => '',
            'tika_server_host' => '',
            'tika_server_port' => 9998,
            'tools_exiftool' => '',
            'tools_pdfinfo' => '',
            'mapping_base_directory' => 'EXT:extractor/Configuration/Services/',
            'mapping_configuration' => ''
        ],
```

---

Is it possible that it has to do with some Middleware stuff or Server/Response Request Objects?.

**Comment by josefglatz** [comment]
@xperseguers if you need some more infos or infos about the environment, please contact me in TYPO3 Slack :)

**Comment by kaystrobach** [comment]
@josefglatz maybe you checkout the pr #17 - feedback would be awesome!

**Comment by xperseguers** [comment]
Please check master branch and report if this still happens.
