### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by hirnschmalz** [xperseguers/t3ext-extractor#14]
Hi there,

I have troubles with the tika extraction. During extraction I get the following messages.

```
org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: org.xerial's sqlite-jdbc is not loaded.
Please provide the jar on your classpath to parse sqlite files.
See tika-parsers/pom.xml for the correct version.
org.apache.tika.config.InitializableProblemHandler$3 handleInitializableProblem
WARNING: J2KImageReader not loaded. JPEG2000 files will not be processed.
See https://pdfbox.apache.org/2.0/dependencies.html#jai-image-io
for optional dependencies.
```

Any ideas how to resolve this?

I'm using the master branch of `EXT:extractor` and `tika` in version `1.20`

**Comment by xperseguers** [comment]
Sounds like a problem in tika, not in EXT:extractor. Just googled your problem and found this: https://stackoverflow.com/questions/48970160/how-do-i-configure-the-pom-xml-of-tika-to-stop-getting-all-the-license-dependenc

HTH

**Comment by hirnschmalz** [comment]
I also stumbled upon this article, but I couldn't figure out how to set these dependencies in `jar` mode.

**Comment by hirnschmalz** [comment]
I was able to fix this by using a `server` mode.

**Comment by xperseguers** [comment]
ok, server is anyway much more efficient :)
