### ISSUE TITLE
Check if $values  is_iterable ?

### ISSUE THREAD

**Issue by hrdyy** [xperseguers/t3ext-extractor#16]
https://github.com/xperseguers/t3ext-extractor/blob/574f165cfe43bcea38a15f5edb0609999dbf28a3/Classes/Service/Php/PhpService.php#L245

got an issue where values where ' '  so there for i got an Invalid argument supplied for foreach()  Exception.

**Comment by kaystrobach** [comment]
can you please check with #17  thank you!

**Comment by xperseguers** [comment]
This code does not exist anymore. It has been replaced as part of https://github.com/xperseguers/t3ext-extractor/pull/10/commits/12782ca4a33d7c4c9bd27ee222b060ca85fe285b
