### ISSUE TITLE
TYPO3_DB moved to extension

### ISSUE THREAD

**Issue by FireLizard** [xperseguers/t3ext-extractor#20]
As described in [Breaking: #80929 - TYPO3_DB moved to extension](https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Breaking-80929-TYPO3_DBMovedToExtension.html) the `$GLOBALS['TYPO3_DB']` does not exist anymore since TYPO3 CMS v9.0

For example when calling this:
https://github.com/xperseguers/t3ext-extractor/blob/d271c840e21f250fc07f54550bdfec7fbcee17b8/Classes/Service/Extraction/AbstractExtractionService.php#L466
it throws the error `Call to a member function exec_SELECTgetSingleRow() on null`.

**Comment by xperseguers** [comment]
This is fixed since 061995eef57748ef1353822b81d02ebbd24531e7
