### ISSUE TITLE
Add support "Flash" exif data

### ISSUE THREAD

**Issue by fnagel** [xperseguers/t3ext-extractor#27]
It would be great if this extension would support the "Flash" exif data field. 

See EXT:metadata for example: 
https://github.com/fabarea/metadata/blob/master/Classes/Index/ImageMetadataExtractor.php#L276
https://github.com/fabarea/metadata/blob/master/Configuration/TCA/Overrides/sys_file_metadata.php#L108

**Comment by xperseguers** [comment]
This field does not seem to exist in TYPO3 v8. Did you check when it started to be available?

**Comment by xperseguers** [comment]
ah... actually added by EXT:metadata, not part of the core. Wanna create a PR?

**Comment by fnagel** [comment]
Yes, I able to provide a PR. Not sure when I'm able to allocate some time, but I'm willing to invest some time for a private project :-)

**Comment by fnagel** [comment]
@xperseguers Created a PR for this, see #30 :-D

**Comment by MediKathi** [comment]
Hello,

in some images the Flash information is stored as String like "No Flash, did not Fire". Therefore the extraction throws an error.

**Comment by fnagel** [comment]
@MediKathi Please create a new ticket if you assume this is a bug. Please include the error message and a example image.
