### ISSUE TITLE
Extractor does not seem to do anything: Hook ignored?

### ISSUE THREAD

**Issue by subnoodle** [xperseguers/t3ext-extractor#28]
Dear Xavier,

we wanted to use you extractor-extension.
While meta data extraction it's working in the mapping tool of the extension settings and it's writing logs to the custom logger, an upload in filelist does not seem to trigger the ExtendedFileUtility hook processData_postProcessAction.

Indeed, Extractor seems do do nothing at all: It's there but seemingly not called for filelist updloads.

We tried it with Typo3-versions 8 and 9, both composer installations.

Could you imagine what prevents Extractor from being called?

We tried also output of debug messages in line 49 of file Classes/Hook/FileUploadHook.php

Any hint / help would be highly appreciated.

Thank you very much, Thomas

**Comment by j-schumann** [comment]
Details to the above report:

When the line
```php
$GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['t3lib/class.t3lib_extfilefunc.php']['processData'][]
= \Causal\Extractor\Hook\FileUploadHook::class; 
```
is added in the ext_localconf.php the extension starts to do something under Typo 8.7.34.
This line was removed from that file in the following commit: https://github.com/xperseguers/t3ext-extractor/commit/9cec9899041d789af24e35c7638d929812ddefbe#diff-650ba9004d55b4534a27f8ad3463dc21L28

But the surrounding "if" suggests it should only be necessary (working?) in Typo < 7.5. What is the correct way to register a hook in current Typo versions? The documentation for 8.7 still uses that method: https://docs.typo3.org/m/typo3/reference-coreapi/8.7/en-us/ApiOverview/Hooks/Configuration/Index.html

Although the extension reacts again to the hook with this line, it still fails processing because of #26.

**Comment by derhansen** [comment]
I agree on this one. The hook is never called, since it is not registered in `ext_localconf.php`.

**Comment by xperseguers** [comment]
All the extractor services are indeed registered in `ext_localconf.php`: https://github.com/xperseguers/t3ext-extractor/blob/master/ext_localconf.php#L15-L32

You can check it is "seen" by TYPO3 by using the Backend module Reports:

<img width="894" alt="TYPO3_v10__TYPO3_CMS_11_0_0-dev_" src="https://user-images.githubusercontent.com/646805/89153191-b64a7400-d564-11ea-83ac-46a6e4b5f0bd.png">

**Comment by derhansen** [comment]
Yes, this is right. The services are all registered, but the `processData_postProcessAction` Hook is not registered any more, so the implementation of `processData_postProcessAction` in `Hook/FileUploadHook.php` is not called.

**Comment by xperseguers** [comment]
Since I'm pretty sure the extraction works in my cases, can you please give the concrete info on your setup? I read about  "current TYPO3 version(s)" and TYPO3 v8. Are you on v8, v9 or v10?

**Comment by xperseguers** [comment]
_(I just think that possibly it works for me because I'm always using EXT:image_autoresize and this ext explicitly calls the extractors)_

**Comment by derhansen** [comment]
I'm on version 8.7 ELTS. Upgraded the extension from 1.5.1 to 1.7.2, where the automatic extraction of metadata stopped. Re-Adding the hook registration as suggested by @j-schumann fixes the problem.

**Comment by xperseguers** [comment]
just tested on v10 (actually even master branch) and it works.

**Comment by derhansen** [comment]
OK, verified this now. Indeed, the hook registration is not required any more. I think this issue has been reported because of #26.

**Comment by xperseguers** [comment]
So you confirm this bug is faulty and should be closed? Because I just tried with v8 and this works for me.

**Comment by xperseguers** [comment]
Possibly I should get rid of the hook implementation altogether, I guess I just forgot to remove that file.

**Comment by derhansen** [comment]
Yes, this works fine on v8.7
