### ISSUE TITLE
ExifTool not detected and usable after migration to TYPO3 10.4

### ISSUE THREAD

**Issue by responseinformationsdesign** [xperseguers/t3ext-extractor#46]
After migration to TYPO3 10.4 exiftool (version) is not detected any more (under extension configuration) and therefore can´t be used. If nevertheless activated there is an error on file upload.
Btw. nothing (machine, version, path, ...) has changed besides of TYPO3. No problems under TYPO3 9.5 before.

**Comment by xperseguers** [comment]
It's properly detected in my v10 install:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/646805/164172778-8b1dbfd0-22b6-4e43-b54f-5490299e3573.png">

I just tried to upload a file (and ensured exiftool was invoked): no problems!

**Comment by responseinformationsdesign** [comment]
All affected installations are windows based. Which version of php do you use?

**Comment by xperseguers** [comment]
PHP 7.4.21

**Comment by xperseguers** [comment]
I've no Windows environment to debug, sorry.

**Comment by responseinformationsdesign** [comment]
For the moment I have no problems anymore with:

- Windows / TYPO3 10.4.40 / PHP 7.4.33
- Windows / TYPO3 11.5.32 / PHP 8.1.25

Therefore I think this issue can be closed.

**Comment by xperseguers** [comment]
thanks for the feedback.
