### ISSUE TITLE
Meta Data Problems

### ISSUE THREAD

**Issue by MediKathi** [xperseguers/t3ext-extractor#48]
Hello,
the Problem given in https://github.com/xperseguers/t3ext-extractor/issues/39 still remains.
This time there was an array given instead of a string.

Also I got several errors with the iso_speed
```
An exception occurred while executing 'INSERT INTO `sys_file_metadata` (`file`, `pid`, `crdate`, `tstamp`, `cruser_id`, `l10n_diffsource`, `color_space`, `height`, `width`, `unit`, `camera_make`, `camera_model`, `shutter_speed`, `focal_length`, `iso_speed`, `aperture`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [323, 0, 1651479325, 1651479325, 22, "", "RGB", 1280, 1920, "px", "Canon", "Canon PowerShot G3 X", "1\/640", 14.6, "125, 0", 5]: Data truncated for column 'iso_speed' at row 1 
```

**Comment by davidlemaitre** [comment]
Facing the same issue with some images imported from a custom import command. A workaround solution is to change column type to VARCHAR(10)

**Comment by LeoniePhiline** [comment]
@xperseguers Would you mind merging #53 and releasing `v2.2.1`?

Thanks!
