### ISSUE TITLE
phar fails with OPCache - getID3 phar should be extracted

### ISSUE THREAD

**Issue by LeoniePhiline** [xperseguers/t3ext-extractor#5]
Hi!

Thanks for building EXT:extractor!

We came across issues with including the /vendor/autoload.php inside Libraries/james-heinrich-getid3.phar.

This throws: 

`PHP Warning:  include(): Failed opening 'phar:///absolute/path/to/public_html/typo3conf/ext/extractor/Libraries/james-heinrich-getid3.phar/vendor/autoload.php' for inclusion (include_path='.:/usr/local/lib/php')`

Depending on OpCache state, it can also succeed on the first include, but then fail one step further:

`PHP Fatal error:  require_once(): Failed opening required 'phar:///absolute/path/to/public_html/typo3conf/ext/extractor/Libraries/james-heinrich-getid3.phar/vendor/composer/autoload_real.php' (include_path='.:/usr/local/lib/php') in phar:///absolute/path/to/public_html/typo3conf/ext/extractor/Libraries/james-heinrich-getid3.phar/vendor/autoload.php on line 5`

In any case, it leads to an autoload failure:
`PHP Fatal error:  Uncaught Error: Class 'getID3' not found`

All this happens in https://github.com/xperseguers/t3ext-extractor/blob/master/Classes/Service/Php/PhpService.php#L165

Other possible reasons like bad file permissions, ionCube Loader issues etc. are out of the picture, due to this test script:

Version 1 fails (with: `PHP Warning: include() failed opening '[...].phar/vendor/autoload.php' for inclusion` + `PHP Fatal error: Class getID3 not found`):

```
<?php
        include 'phar:///absolute/path/to/public_html/typo3conf/ext/extractor/Libraries/james-heinrich-getid3.phar/vendor/autoload.php';

        $getID3 = new \getID3();
        $getID3->setOption(array('encoding' => 'UTF-8'));
        var_dump($getID3);
```

Version 2, with `opcache_reset()`, works:
```
<?php
        // Reset OpCache before attempting phar include:
        opcache_reset();

        include 'phar:///home/trefwoordp/domains/trefwoord.nl/private_html/typo3conf/ext/extractor/Libraries/james-heinrich-getid3.phar/vendor/autoload.php';

        $getID3 = new \getID3();
        $getID3->setOption(array('encoding' => 'UTF-8'));
        var_dump($getID3);
```

Note: The test script must run on the server, requested via HTTP. The Command line (e.g. via `php -r`) does not share the same OpCache cache.

OpCache, which is widely used, is known to have problems with PHAR files:

https://bugs.php.net/bug.php?id=66569&edit=2
https://github.com/zendtech/ZendOptimizerPlus/issues/149
https://github.com/zendtech/ZendOptimizerPlus/issues/115

The only solution (since calling `opcache_reset()` each time in the script is hacky and causes performance issues) would be to replace the phar file by its extracted content as directory-based Library.

Since you are using composer anyway, which can easily deal with directory-based packages, I would ask you to kindly replace the Library phar with a directory-based Library (as e.g. all typo3_src vendor dependencies).

Thank you!

**Comment by LeoniePhiline** [comment]
Loading the extracted phar:

```diff
diff --git a/typo3conf/ext/extractor/Classes/Service/Php/PhpService.php b/typo3conf/ext/extractor/Classes/Service/Php/PhpService.php
index f1d60a61..db50f4c4 100644
--- a/typo3conf/ext/extractor/Classes/Service/Php/PhpService.php
+++ b/typo3conf/ext/extractor/Classes/Service/Php/PhpService.php
@@ -160,10 +160,7 @@ class PhpService extends AbstractService
         static::getLogger()->debug('Extracting metadata with GetID3 library');
 
         // Require 3rd-party libraries, in case TYPO3 does not run in composer mode
-        $pharFileName = \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('extractor') . 'Libraries/james-heinrich-getid3.phar';
-        if (is_file($pharFileName)) {
-            @include 'phar://' . $pharFileName . '/vendor/autoload.php';
-        }
+        include \TYPO3\CMS\Core\Utility\ExtensionManagementUtility::extPath('extractor') . 'Libraries/vendor/autoload.php';
 
         $getID3 = new \getID3();
         $getID3->setOption(array('encoding' => 'UTF-8'));
```

![extracted-autoload-getid3](https://user-images.githubusercontent.com/22329650/37657166-85a2834e-2c4a-11e8-9e0c-addaf3f2cda6.png)

**Comment by xperseguers** [comment]
In the mean time, solution is to install this extension through composer and not through a zip package (downloaded off TER).
