### ISSUE TITLE
Metadata in image results in Devision by zero error

### ISSUE THREAD

**Issue by bmheins** [xperseguers/t3ext-extractor#57]
![bug-extractor-image](https://user-images.githubusercontent.com/32935316/228273365-73581eef-4bf7-426d-9984-bdf8daa381cc.jpg)

The image above leads to a "Division by zero" exception when uploading to TYPO3. It's thrown in the extractor extensions due to its EXIF metadata; in it the value "0/0" is set for "GPSAltitude" (and in some other places, see image below). (The image is a "real life" example; we stumbled upon this error in a production context. I just changed the image, not the metadata.)

Your extension tries to translate this relation into an absolute value and therefore throws the error.

In https://exiv2.org/tags.html for "Image.LensInfo" the value "0/0" is set for "unknown". Though this is is not the case for "GPSAltitude", but the value itself seems me to be legit and should IMHO be handled.

In the image above there are several occurances of the value "0/0":

![image](https://user-images.githubusercontent.com/32935316/228272548-5f1c5bcf-36f5-4ea2-8c1d-59c787f33d22.png)

**Comment by sfroemkenjw** [comment]
Hello @xperseguers 

Thank you for fixing that issue in Dec. 2022. Do see a chance to release a new version?

Stefan

**Comment by xperseguers** [comment]
Done right now. Thanks for pinging :)
