### ISSUE TITLE
Error when uploading files: "DOMDocument::loadXML(): Start tag expected, '&lt;' not found in Entity"

### ISSUE THREAD

**Issue by seirerman** [xperseguers/t3ext-extractor#63]
Extractor works mostly fine, but I get fatal errors when uploading certain files:
`PHP Warning: DOMDocument::loadXML(): Start tag expected, '&lt;' not found in Entity, line: 1 in /var/dvt/html/t3tiro/web/typo3conf/ext/extractor/Classes/Service/Php/PhpService.php line 265 | TYPO3\CMS\Core\Error\Exception thrown in file /var/dvt/html/t3tiro/web/typo3/sysext/core/Classes/Error/ErrorHandler.php in line 137`
This leads to TYPO3 uploading the file despite the error, but not creating a sys_file_metadata record and editors not being able to edit the metadata within TYPO3.

You can use this [PDF](https://www.tirol.gv.at/fileadmin/_test_/demo/WR-B-2691_WE_GmbH.pdf) that can hopefully reproduce this error during the upload process. A coworker of mine who specializes in automated document creation checked the file for PDF syntax and also did a preflight check (no idea what that is :-) ) in Adobe Acrobat. He said the file looks fine.

Uploading the same file without extractor produces no errors. Any idea what causes this?

- TYPO3 11.5.31
- extractor 2.3.0
- exiftool 12.60
- pdfinfo 0.26.5
- basic.enable_tika=0
- basic.enable_tools_exiftool=1
- basic.enable_tools_pdfinfo=1
- basic.enable_php=1

**Comment by seirerman** [comment]
Thank you for checking the file. I'll forward that to my coworker...

**Comment by xperseguers** [comment]
Still investigating....

The PDF is encoded with LF, whereas the code skips CR + LF ("DOS"/Windows format), that's why there is a character offset

**Comment by seirerman** [comment]
I've added your patch, but now I occationally get this error:
`Core: Error handler (BE): PHP Warning: DOMDocument::loadXML(): ParsePI: PI xpacket never end ... in Entity, line: 46 in /typo3conf/ext/extractor/Classes/Service/Php/PhpService.php line 268`

**Comment by xperseguers** [comment]
Certainly some other oddity with the parsing (which I didn’t write in the first place). Could you please send me an example document causing the problem so I could double check what happens exactly?

**Comment by seirerman** [comment]
I found [another file](https://www.tirol.gv.at/fileadmin/_test_/temp/Spielaktiv_Plakat_2023.pdf) that causes a ParsePI error.
The file gets uploaded, a sys_file_metadata records is created and no error is visible for the editor.
But there are 3 warnings in the protocol module:

- Core: Error handler (BE): PHP Warning: DOMDocument::loadXML(): ParsePI: PI xpacket never end ... in Entity, line: 52 in /var/dvt/html/t3tiro/web/typo3conf/ext/extractor/Classes/Service/Php/PhpService.php line 268
- Core: Error handler (BE): PHP Warning: DOMDocument::loadXML(): ParsePI: PI xpacket never end ... in Entity, line: 614 in /var/dvt/html/t3tiro/web/typo3conf/ext/extractor/Classes/Service/Php/PhpService.php line 268
- Core: Error handler (BE): PHP Warning: DOMDocument::loadXML(): ParsePI: PI xpacket never end ... in Entity, line: 620 in /var/dvt/html/t3tiro/web/typo3conf/ext/extractor/Classes/Service/Php/PhpService.php line 268

Unfortunately I don't have the tools to check the integrity of PDF files like this one...

**Comment by tehplague** [comment]
It would be nice if `extractor` gracefully handled metadata extraction errors by catching and logging the problem but returning with an empty `$metadata` array. That way, TYPO3 could at least insert a `sys_file_metadata` record for an editor to edit subsequently. With the current implementation, TYPO3 ends up without this record, thus disabling the edit metadata functionality for the file in the backend.
I monkey-patched `extractor` here by wrapping `extractMetadataFromPdf` with `try ... catch`.
