### ISSUE TITLE
Extension seems to be not loaded properly

### ISSUE THREAD

**Issue by izaquieltome** [xperseguers/t3ext-extractor#70]
Hello guys, hopefully you can help me here:
I have a almost fresh Typo3 12.4.8 installation - as I am a Photogorapher, metadata is prettyx important to me. 
So I wanted to use this extension again, since its available vor v12 and I really loved it in the past.

Now my problem is:
I have a composer-installation, use typo3 12.4.8 and extractor 2.4.2 - my PHP Version is 8.2 (I also tried with 8.1)

So it gets listed in the extensions-Module, I can change the settings - but that's all.
The Fields are created by the Install Tool for Database Compare - but they are not shown in Files in the Filelist Module.
Neither doest it seem to extract any information. 
Not on already existing imagers, not on freshly uploaded images. 

I get absolutely no errors (not in Typo3, not in Server-Logs ... ).

Maybe anyone of you has some idea how to fix this, thanks in advance.

Best, Iza

**Comment by wazum** [comment]
I have the same issue with TYPO3 11.5.33,
the JavaScript is not executed (that is how far I debugged the issue).

**Comment by xperseguers** [comment]
Which JS? BTW, extraction of metadata does not suppose the use of any JS.

**Comment by xperseguers** [comment]
Naturally you have this for your fileadmin storage?

<img width="537" alt="image" src="https://github.com/xperseguers/t3ext-extractor/assets/646805/fc50e359-6ecd-4810-8a63-a373c76e7223">

Regarding "missing fields", it is supposed to be added and managed by system extension filemetadata, this is a dependency but maybe, somehow, it is not enabled on your side?

**Comment by izaquieltome** [comment]
As far as I can see it, this is not completly correct. The extension "extractor" provides additional fields like cameradata (model, make, lens), shutter_speed etc. - those are not provided by the system extension filemetadata. 
I checked this with a look into the ext_tables.sql and the TCA overrides from the extension to be shure.

So this fields should be provided by the extension "extractor" - but are not. the extension could only generate the sql-fields in the database with the database compare tool from Typo3 - but as said - they are not shown in the Backend.

Regarding extraction: Yes, my fileadmin has this checkbox active - but at least the scheduler task should extract the data afterwards, when executed - at least it did in the past.

**Comment by xperseguers** [comment]
I confirm that, but they are provided by EXT:extractor (see https://github.com/xperseguers/t3ext-extractor/blob/master/Configuration/TCA/Overrides/sys_file_metadata.php), somehow, it looks like the type of file has changed.

**Comment by xperseguers** [comment]
Problem must be there: https://github.com/xperseguers/t3ext-extractor/blob/master/Configuration/TCA/Overrides/sys_file_metadata.php#L215 as in TYPO3 v12 (at least), the system extensions have forcibly been moved to `vendor/` just as any other composer packages.
