### ISSUE TITLE
Undefined Array key in ColorSpace.php

### ISSUE THREAD

**Issue by izaquieltome** [xperseguers/t3ext-extractor#71]
When I upload an image, I now get the following Error Message in Protocols:
Core: Error handler (BE): PHP Warning:  Undefined array key 1 in  /var/www/vhosts/izaquiel.at/httpdocs/vendor/causal/extractor/Classes/Utility/ColorSpace.php  line 80

This Error gets fired 8 times per image. The Server Error Log File doesn't give any more hints for this.

This also seems to result in an empty Field "Color Space" - as well for "white balance mode" and "lens" - and a value of "0" for "iso Speed".

My Typo3 12 is runnning in composer Mode with PHP 8.2 (but also tried with PHP 8.1)

**Comment by xperseguers** [comment]
Thanks for reporting. This looks like PHP 8-related errors and we will fix them. Those errors shouldn't occur in production mode though, so if you are getting this on your (production) website, be sure to switch to production mode instead of development/debugging.
