### ISSUE TITLE
PDF metadata - Data too long for column 'publisher' at row 1

### ISSUE THREAD

**Issue by medarob** [xperseguers/t3ext-extractor#85]
Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'INSERT INTO `sys_file_metadata` (`file`, `pid`, `crdate`, `tstamp`, `cruser_id`, `l10n_diffsource`, `width`, `height`, `content_creation_date`, `content_modification_date`, `creator_tool`, `pages`, `title`, `unit`, `publisher`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [27273, 0, 1714654440, 1714654440, 2, "", 339, 191, 1713787124, 1714654283, "macOS Version 14.4.1 (Build 23E224) Quartz PDFContext", "89", "Oracle", "mm", "macOS Version 14.4.1 (Build 23E224) Quartz PDFContext"]: Data too long for column 'publisher' at row 1 | Doctrine\DBAL\Exception\DriverException thrown in file /var/www/typo3/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 128. Requested URL: https://domain.tld/typo3/ajax/file/process?token=--AnonymizedToken-- 

Core: Exception handler (WEB): Uncaught TYPO3 Exception: An exception occurred while executing 'INSERT INTO `sys_file_metadata` (`file`, `pid`, `crdate`, `tstamp`, `cruser_id`, `l10n_diffsource`, `width`, `height`, `content_creation_date`, `content_modification_date`, `creator`, `creator_tool`, `unit`, `pages`, `publisher`, `title`) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [27267, 0, 1714653959, 1714653959, 2, "", 339, 191, 1712672533, 1712672560, "PDF-XChange Office Addin", "PDF-XChange Standard (10.2.1 build 385) [GDI] [Windows 10 Enterprise x64 (Build 19044)]", "mm", "17", "PDF-XChange Standard (10.2.1 build 385) [GDI] [Windows 10 Enterprise x64 (Build 19044)]", "Pr\u00e4sentationstitel in max. zwei Zeilen"]: Data too long for column 'publisher' at row 1 | Doctrine\DBAL\Exception\DriverException thrown in file /var/www/typo3/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php in line 128. Requested URL: https://domain.tld/typo3/ajax/file/process?token=--AnonymizedToken-- 

It seems like that `macOS Version 14.4.1 (Build 23E224) Quartz PDFContext` and `PDF-XChange Standard (10.2.1 build 385) [GDI] [Windows 10 Enterprise x64 (Build 19044)]` are too long for the `publisher` field?

The resulting problem is, that the metadata fields in TYPO3 can't be edited for those files because they are not available:
![grafik](https://github.com/xperseguers/t3ext-extractor/assets/33951787/a8ebaa14-586a-4832-b9a0-7a90bea97bcc)

Currently I'm not sure where I can change this. It would be better if the field could accept a longer value.

**Comment by medarob** [comment]
This seems to be a TYPO3 restriction/bug and can be changed with the following code in `ext_tables.sql`.
The default value for the publisher field is 45 characters. This changes it to 100.

```
# Table structure for table 'sys_file_metadata'
#
# Allow publisher field with longer entries
 
CREATE TABLE sys_file_metadata (
publisher varchar(100) DEFAULT ''
);
```

**Comment by LeoniePhiline** [comment]
I've reported this issue in the TYPO3 issue tracker, since the database field is part of the core extension `filemetadata`.

https://forge.typo3.org/issues/104872
